apiVersion: v1
kind: Service
metadata:
  name: notejam-service
  annotations: 
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: notejam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
